# Site settings
title: MEGABOX
email: dhli@cs.hku.hk
description: > # this means to ignore newlines until "baseurl:"
  Open-access MEGAHIT assemblies of big, public metagenome sequencing datasets.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hku-bal.github.io/megabox" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  hku-bal

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)